name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [2.4.x, 2.5.x, 2.6.x]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{  matrix.ruby_version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: install bundler
      run: |
        gem install bundler --no-document
    - name: Cache gems
      uses: actions/cache@preview
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: bundle install
      run: |
        bundle install --jobs 4 --retry 3 --path vendor/bundle
    - name: Run test
      run: |
        bundle exec rake
